# Generated by Django 5.1.4 on 2025-01-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.FloatField()),
                ('seat', models.CharField(max_length=128, null=True)),
                ('note', models.CharField(max_length=2048, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.category')),
            ],
            options={
                'ordering': ('-modified_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
